#!/usr/bin/env python3
"""박지별 검색용 정적 페이지(spot/<id>/index.html), 목록(spot/index.html), sitemap.xml을 만든다.

    python3 scripts/build-spot-pages.py            # 생성
    python3 scripts/build-spot-pages.py --dry-run  # 파일을 쓰지 않고 요약만

공개 범위: 이름·지역·[뷰/특징](view_brief)·고도·지형·난이도·거리·코스 유형만.
좌표·들머리 주소·코스/피칭/팁·작성자 SNS·사용자 사진은 넣지 않는다. 상세는 map.html?id=<id>로 넘긴다.

제외:
  - view_brief에 국립·도립·군립공원이 언급된 박지 (공원 내 야영 금지, 검색 홍보 방지)
  - scripts/spot-pages-exclude.json 의 "ids"에 적은 박지
제외되거나 DB에서 사라진 박지의 기존 페이지는 지운다.
"""
import html
import json
import os
import re
import shutil
import sys
import urllib.parse
import urllib.request
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://romanticroute.kr"
OUT_DIR = os.path.join(ROOT, "spot")
EXCLUDE_FILE = os.path.join(ROOT, "scripts", "spot-pages-exclude.json")
SELECT = ("id,region,cityName,spot_main,spot_sub,elevation,terrain,difficulty,"
          "distance_km,course_type,view_brief,created_at")
PARK_RE = re.compile(r"(국립|도립|군립)공원")
REGION_ORDER = ["서울/인천", "경기", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"]
REGION_ALIAS = {"서울": "서울/인천", "인천": "서울/인천", "대전": "충남", "세종": "충남",
                "대구": "경북", "부산": "경남", "울산": "경남", "광주": "전남"}
GENERATED_MARK = "<!-- generated by scripts/build-spot-pages.py -->"


def supabase_config():
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_PUBLISHABLE_KEY") or os.environ.get("SUPABASE_ANON_KEY")
    if url and key:
        return url, key
    # 사이트에 이미 공개된 publishable 키를 그대로 쓴다 (anon 권한 = 공개 컬럼만 읽힘)
    src = open(os.path.join(ROOT, "map.html"), encoding="utf-8").read()
    url = re.search(r"window\.SUPABASE_URL = '([^']+)'", src).group(1)
    key = re.search(r"window\.SUPABASE_ANON_KEY = '([^']+)'", src).group(1)
    return url, key


def fetch_spots():
    url, key = supabase_config()
    req = urllib.request.Request(
        f"{url}/rest/v1/spots?select={SELECT}&order=id.asc",
        headers={"apikey": key, "Authorization": "Bearer " + key},
    )
    with urllib.request.urlopen(req, timeout=30) as res:
        return json.load(res)


def load_excluded_ids():
    if not os.path.exists(EXCLUDE_FILE):
        return set()
    data = json.load(open(EXCLUDE_FILE, encoding="utf-8"))
    return {str(x).strip() for x in data.get("ids", [])}


def region_of(row):
    r = str(row.get("region") or "").strip()
    return REGION_ALIAS.get(r, r) or "기타"


def clean_text(s):
    return re.sub(r"\s+", " ", str(s or "").replace("\\n", "\n")).strip()


def fmt_num(v):
    if v is None or v == "":
        return ""
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v).strip()
    return str(int(f)) if f == int(f) else f"{f:.1f}".rstrip("0").rstrip(".")


def difficulty_of(row):
    try:
        d = int(str(row.get("difficulty") or "3").strip())
    except ValueError:
        d = 3
    d = min(max(d, 1), 5)
    if d <= 2:
        return d, "쉬움", "easy"
    if d >= 4:
        return d, "어려움", "hard"
    return d, "보통", "mid"


def terrains_of(row):
    return [t.strip() for t in str(row.get("terrain") or "").split(",") if t.strip()]


def display_name(row):
    main = clean_text(row.get("spot_main"))
    sub = clean_text(row.get("spot_sub"))
    if sub and sub in main:
        sub = ""
    return main, sub


def esc(s):
    return html.escape(str(s), quote=True)


def json_ld(obj):
    # </script> 조기 종료 방지
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


STYLE = """
:root{color-scheme:dark}
*{box-sizing:border-box}
body{margin:0;background:#05060a;color:#e2e8f0;font-family:-apple-system,BlinkMacSystemFont,"Apple SD Gothic Neo","Pretendard","Noto Sans KR",sans-serif;line-height:1.65;-webkit-font-smoothing:antialiased}
a{color:#fde047}
a:focus-visible,button:focus-visible{outline:2px solid #fde047;outline-offset:2px}
.wrap{max-width:720px;margin:0 auto;padding:20px 18px 48px}
.top{display:flex;align-items:center;gap:8px;text-decoration:none;color:#fff;font-weight:800;font-size:1.05rem}
.top img{width:28px;height:28px}
.crumb{margin:18px 0 6px;font-size:.8rem;color:#94a3b8}
.crumb a{color:#94a3b8}
h1{margin:0;font-size:1.6rem;line-height:1.35;color:#f8fafc;letter-spacing:-.02em}
.sub{margin:4px 0 0;color:#cbd5e1;font-size:1rem}
.badges{display:flex;flex-wrap:wrap;gap:6px;margin:14px 0 4px;padding:0;list-style:none}
.badges li{font-size:.78rem;padding:3px 10px;border-radius:999px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.14);color:#e2e8f0}
.badges .easy{border-color:#10b981;color:#6ee7b7}.badges .mid{border-color:#f59e0b;color:#fcd34d}.badges .hard{border-color:#f43f5e;color:#fda4af}
.card{margin:18px 0;padding:16px;border-radius:14px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1)}
.card h2{margin:0 0 8px;font-size:.95rem;color:#f8fafc}
.card p{margin:0}
.cta{display:block;margin:10px 0 0;padding:12px;border-radius:12px;background:#fde047;color:#111;font-weight:800;text-align:center;text-decoration:none}
.lock{color:#cbd5e1;font-size:.88rem}
.qr{display:none;margin-top:14px;text-align:center;font-size:.8rem;color:#94a3b8}
.qr img{display:block;margin:0 auto 6px;width:160px;height:160px;border-radius:12px;background:#fff;padding:8px}
@media (min-width:900px) and (hover:hover){.qr{display:block}}
.notice{margin:0;padding-left:18px;font-size:.8rem;color:#94a3b8}
.related{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:8px;margin:0;padding:0;list-style:none}
.related a{display:block;padding:10px 12px;border-radius:10px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);color:#e2e8f0;text-decoration:none;font-size:.88rem}
.related small{display:block;color:#94a3b8}
.region{margin:28px 0 8px;font-size:1.1rem;color:#f8fafc}
footer{margin-top:36px;font-size:.75rem;color:#64748b}
"""

HEAD_COMMON = """<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="script-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#000000">
<link rel="icon" type="image/png" href="/logo.png">"""

FOOTER = """<footer>
  <p>실제 정보와 다를 수 있으니 출발 전 현장 상황과 관련 규정을 꼭 확인하세요.</p>
  <p>© 낭만루트 · <a href="/">romanticroute.kr</a></p>
</footer>"""


def spot_page(row, same_region):
    sid = str(row["id"]).strip()
    main, sub = display_name(row)
    city = clean_text(row.get("cityName"))
    region = region_of(row)
    brief = clean_text(row.get("view_brief"))
    d, d_label, d_class = difficulty_of(row)
    elev = fmt_num(row.get("elevation"))
    dist = fmt_num(row.get("distance_km"))
    course = clean_text(row.get("course_type"))
    terrains = terrains_of(row)

    name_full = f"{main} {sub}".strip()
    place = city or region
    title = f"{name_full} 백패킹 - {place} | 낭만루트"
    desc = brief if len(brief) <= 150 else brief[:149].rstrip() + "…"
    if not desc:
        desc = f"{place} {name_full} 백패킹 장소 정보. 낭만루트에서 들머리와 코스를 확인하세요."
    page_url = f"{SITE}/spot/{sid}/"
    map_url = f"{SITE}/map.html?id={urllib.parse.quote(sid)}"
    qr_url = ("https://api.qrserver.com/v1/create-qr-code/?size=320x320&margin=8&data="
              + urllib.parse.quote(map_url, safe=""))

    badges = [f'<li>{esc(region)}{(" · " + esc(city)) if city and city != region else ""}</li>']
    if elev:
        badges.append(f"<li>해발 {esc(elev)}m</li>")
    badges.append(f'<li class="{d_class}">난이도 {esc(d_label)} ({d}/5)</li>')
    if dist:
        badges.append(f"<li>편도 약 {esc(dist)}km</li>" if course == "편도" else f"<li>거리 약 {esc(dist)}km</li>")
    if course and course != "일반":
        badges.append(f"<li>{esc(course)} 코스</li>")
    badges += [f"<li>{esc(t)}</li>" for t in terrains]

    related = "\n".join(
        f'<li><a href="/spot/{esc(r["id"])}/">{esc(" ".join(display_name(r)).strip())}'
        f'<small>{esc(clean_text(r.get("cityName")) or region_of(r))}</small></a></li>'
        for r in same_region
    )

    address = {"@type": "PostalAddress", "addressCountry": "KR", "addressRegion": region}
    if city:
        address["addressLocality"] = city
    ld_place = {
        "@context": "https://schema.org",
        "@type": "TouristAttraction",
        "name": name_full,
        "description": desc,
        "url": page_url,
        "address": address,
        "touristType": "백패킹",
    }
    ld_crumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "낭만루트", "item": f"{SITE}/"},
            {"@type": "ListItem", "position": 2, "name": "박지", "item": f"{SITE}/spot/"},
            {"@type": "ListItem", "position": 3, "name": name_full, "item": page_url},
        ],
    }

    return f"""<!doctype html>
<html lang="ko">
<head>
{GENERATED_MARK}
{HEAD_COMMON}
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<link rel="canonical" href="{esc(page_url)}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="낭만루트">
<meta property="og:locale" content="ko_KR">
<meta property="og:url" content="{esc(page_url)}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:image" content="{SITE}/fulllogoblk.png?v=20260919_v3">
<meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">{json_ld(ld_place)}</script>
<script type="application/ld+json">{json_ld(ld_crumb)}</script>
<style>{STYLE}</style>
</head>
<body>
<div class="wrap">
<a class="top" href="/"><img src="/logo.png" alt="" width="28" height="28">낭만루트</a>
<nav class="crumb" aria-label="현재 위치"><a href="/spot/">박지</a> › <a href="/spot/#{esc(region)}">{esc(region)}</a> › {esc(main)}</nav>
<main>
<h1>{esc(main)}</h1>
{f'<p class="sub">{esc(sub)}</p>' if sub else ''}
<ul class="badges" aria-label="장소 요약">
{"".join(badges)}
</ul>
<section class="card">
<h2>뷰와 특징</h2>
<p>{esc(brief) if brief else '낭만루트에 등록된 백패킹 장소예요.'}</p>
</section>
<section class="card">
<h2>들머리와 코스 정보</h2>
<p class="lock">정확한 위치, 들머리 주소와 내비 연결, 코스·피칭·주의사항은 소중한 장소 보존을 위해 낭만루트에 로그인한 회원에게만 공개돼요.</p>
<a class="cta" href="{esc(map_url)}">낭만루트 지도에서 보기</a>
<div class="qr"><img src="{esc(qr_url)}" alt="휴대폰으로 낭만루트 지도 열기 QR 코드" width="160" height="160" loading="lazy">휴대폰 카메라로 찍으면 바로 열려요</div>
</section>
<section class="card">
<h2>떠나기 전에</h2>
<ul class="notice">
<li>산림 내 화기 사용과 취사는 금지돼요 (산림보호법 제34조).</li>
<li>국립·도립공원 안에서 허가 없이 야영하면 자연공원법 위반이에요.</li>
<li>쓰레기는 되가져오고, 사유지에는 들어가지 마세요.</li>
</ul>
</section>
{f'<section><h2 class="region">{esc(region)}의 다른 박지</h2><ul class="related">{related}</ul></section>' if related else ''}
</main>
{FOOTER}
</div>
</body>
</html>
"""


def index_page(groups, total):
    sections = []
    for region, rows in groups:
        items = "\n".join(
            f'<li><a href="/spot/{esc(r["id"])}/">{esc(" ".join(display_name(r)).strip())}'
            f'<small>{esc(clean_text(r.get("cityName")) or region)}</small></a></li>'
            for r in rows
        )
        sections.append(f'<section><h2 class="region" id="{esc(region)}">{esc(region)} <small>{len(rows)}곳</small></h2>'
                        f'<ul class="related">{items}</ul></section>')
    title = "전국 백패킹 박지 목록 | 낭만루트"
    desc = f"낭만루트에 등록된 전국 백패킹 박지 {total}곳을 지역별로 모았어요. 뷰와 특징, 난이도, 지형을 확인하세요."
    ld = {"@context": "https://schema.org", "@type": "CollectionPage", "name": title,
          "url": f"{SITE}/spot/", "description": desc, "inLanguage": "ko-KR"}
    return f"""<!doctype html>
<html lang="ko">
<head>
{GENERATED_MARK}
{HEAD_COMMON}
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<link rel="canonical" href="{SITE}/spot/">
<meta property="og:type" content="website">
<meta property="og:site_name" content="낭만루트">
<meta property="og:url" content="{SITE}/spot/">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:image" content="{SITE}/fulllogoblk.png?v=20260919_v3">
<script type="application/ld+json">{json_ld(ld)}</script>
<style>{STYLE}</style>
</head>
<body>
<div class="wrap">
<a class="top" href="/"><img src="/logo.png" alt="" width="28" height="28">낭만루트</a>
<main>
<h1 style="margin-top:18px">전국 백패킹 박지</h1>
<p class="sub">지역별 {total}곳. 들머리와 코스는 <a href="{SITE}/map.html">낭만루트 지도</a>에서 로그인 후 확인할 수 있어요.</p>
{"".join(sections)}
</main>
{FOOTER}
</div>
</body>
</html>
"""


def sitemap(ids):
    today = date.today().isoformat()
    urls = [f"  <url>\n    <loc>{SITE}/</loc>\n    <lastmod>{today}</lastmod>\n  </url>",
            f"  <url>\n    <loc>{SITE}/map.html</loc>\n    <lastmod>{today}</lastmod>\n  </url>",
            f"  <url>\n    <loc>{SITE}/spot/</loc>\n    <lastmod>{today}</lastmod>\n  </url>"]
    urls += [f"  <url>\n    <loc>{SITE}/spot/{i}/</loc>\n  </url>" for i in ids]
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(urls) + "\n</urlset>\n")


def write(path, text, dry):
    if dry:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def main():
    dry = "--dry-run" in sys.argv
    rows = [r for r in fetch_spots() if str(r.get("id") or "").strip() and clean_text(r.get("spot_main"))]
    manual = load_excluded_ids()
    park, kept = [], []
    for r in rows:
        sid = str(r["id"]).strip()
        if sid in manual:
            continue
        if PARK_RE.search(r.get("view_brief") or ""):
            park.append(r)
            continue
        kept.append(r)

    by_region = {}
    for r in kept:
        by_region.setdefault(region_of(r), []).append(r)
    for lst in by_region.values():
        lst.sort(key=lambda r: " ".join(display_name(r)))
    order = [g for g in REGION_ORDER if g in by_region] + sorted(g for g in by_region if g not in REGION_ORDER)
    groups = [(g, by_region[g]) for g in order]

    keep_ids = set()
    for r in kept:
        sid = str(r["id"]).strip()
        keep_ids.add(sid)
        peers = [p for p in by_region[region_of(r)] if p is not r][:8]
        write(os.path.join(OUT_DIR, sid, "index.html"), spot_page(r, peers), dry)
    write(os.path.join(OUT_DIR, "index.html"), index_page(groups, len(kept)), dry)

    # 제외됐거나 DB에서 사라진 박지 페이지 삭제 (숫자 id 폴더 중 이 스크립트가 만든 것만)
    removed = []
    if os.path.isdir(OUT_DIR):
        for name in os.listdir(OUT_DIR):
            p = os.path.join(OUT_DIR, name)
            if not os.path.isdir(p) or name in keep_ids:
                continue
            idx = os.path.join(p, "index.html")
            if os.path.exists(idx) and GENERATED_MARK in open(idx, encoding="utf-8").read(400):
                removed.append(name)
                if not dry:
                    shutil.rmtree(p)

    ids_sorted = sorted(keep_ids, key=lambda x: (not x.isdigit(), int(x) if x.isdigit() else 0, x))
    write(os.path.join(ROOT, "sitemap.xml"), sitemap(ids_sorted), dry)

    print(f"spots {len(rows)} | pages {len(kept)} | park-excluded {len(park)} | manual-excluded {len(manual)} | removed {len(removed)}"
          + (" (dry-run)" if dry else ""))
    if park:
        print("park-excluded:", ", ".join(f'{r["id"]}:{clean_text(r.get("spot_main"))}' for r in park))


if __name__ == "__main__":
    main()
